#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail
umask 077

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "Shared Agent Memory setup"

stage "Ollama: local models"
say "Redis Agent Memory will use local Ollama models for generation and embeddings."
if ! command -v ollama >/dev/null 2>&1; then
  warn "Ollama is required. Install it from https://ollama.com/download and re-run this wizard."
  exit 1
fi
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"
if ! curl --fail --silent --show-error http://127.0.0.1:11434/api/version >/dev/null 2>&1; then
  if command -v brew >/dev/null 2>&1; then
    step "Starting Ollama as a Homebrew user service."
    brew services start ollama
  else
    warn "Ollama is installed but not running. Start 'ollama serve' and re-run this wizard."
    exit 1
  fi
fi
step "Pulling qwen3:8b for generation."
ollama pull qwen3:8b
step "Pulling nomic-embed-text for 768-dimensional embeddings."
ollama pull nomic-embed-text
write_env OLLAMA_API_BASE "http://host.docker.internal:11434"
write_env GENERATION_MODEL "ollama/qwen3:8b"
write_env FAST_MODEL "ollama/qwen3:8b"
write_env SLOW_MODEL "ollama/qwen3:8b"
write_env EMBEDDING_MODEL "ollama/nomic-embed-text"
write_env REDISVL_VECTOR_DIMENSIONS "768"
write_env REDISVL_INDEX_NAME "memory_records_ollama_768"

stage "Agents: unique MCP keys"
say "We'll generate a different random key for each agent and keep them only in the ignored .env."
for command_name in openssl jq; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    warn "$command_name is required to generate the local keys."
    exit 1
  fi
done
SHARED_MEMORY_CODEX_KEY=$(openssl rand -hex 32)
SHARED_MEMORY_GROK_KEY=$(openssl rand -hex 32)
SHARED_MEMORY_COMPOSER_KEY=$(openssl rand -hex 32)
SHARED_MEMORY_ORCA_KEY=$(openssl rand -hex 32)
MEMORY_AGENT_KEYS_JSON=$(jq -cn \
  --arg codex "$SHARED_MEMORY_CODEX_KEY" \
  --arg grok "$SHARED_MEMORY_GROK_KEY" \
  --arg composer "$SHARED_MEMORY_COMPOSER_KEY" \
  --arg orca "$SHARED_MEMORY_ORCA_KEY" \
  '{codex:$codex,grok:$grok,composer:$composer,orca:$orca}')
write_env SHARED_MEMORY_CODEX_KEY "$SHARED_MEMORY_CODEX_KEY"
write_env SHARED_MEMORY_GROK_KEY "$SHARED_MEMORY_GROK_KEY"
write_env SHARED_MEMORY_COMPOSER_KEY "$SHARED_MEMORY_COMPOSER_KEY"
write_env SHARED_MEMORY_ORCA_KEY "$SHARED_MEMORY_ORCA_KEY"
write_env MEMORY_AGENT_KEYS_JSON "$MEMORY_AGENT_KEYS_JSON"
ask MEMORY_WORKSPACE_ID "Workspace ID authorized for shared memory [default: local]:"
MEMORY_WORKSPACE_ID=${MEMORY_WORKSPACE_ID:-local}
if [[ ! "$MEMORY_WORKSPACE_ID" =~ ^[a-zA-Z0-9][a-zA-Z0-9._:-]{0,127}$ ]]; then
  warn "Workspace ID contains unsupported characters."
  exit 1
fi
write_env MEMORY_WORKSPACE_ID "$MEMORY_WORKSPACE_ID"
MEMORY_AGENT_GRANTS_JSON=$(jq -cn --arg workspace "$MEMORY_WORKSPACE_ID" '
  {codex:[{workspaceId:$workspace,projectIds:["*"]}],
   grok:[{workspaceId:$workspace,projectIds:["*"]}],
   composer:[{workspaceId:$workspace,projectIds:["*"]}],
   orca:[{workspaceId:$workspace,projectIds:["*"],allowGlobal:true}]}')
write_env MEMORY_AGENT_GRANTS_JSON "$MEMORY_AGENT_GRANTS_JSON"
chmod 600 "$ENV_FILE"

stage "Docker: start persistent memory"
say "Docker will start Redis, Agent Memory API/worker, and the shared MCP on host loopback."
warn "Redis data persists in a named volume. The down command does not delete that volume."
if confirm "Start the shared memory stack now?"; then
  docker compose -f docker-compose.memory.yml --env-file "$ENV_FILE" up -d --build
else
  SKIPPED+=("start stack: ./bin/memory up")
fi

stage "Sessions: health and environment"
say "New Codex, Cursor, Grok, and Orca sessions must receive their matching key and reload MCP/skills."
if command -v launchctl >/dev/null 2>&1 && confirm "Expose the generated keys to new apps in this macOS login session?"; then
  launchctl setenv SHARED_MEMORY_CODEX_KEY "$SHARED_MEMORY_CODEX_KEY"
  launchctl setenv SHARED_MEMORY_GROK_KEY "$SHARED_MEMORY_GROK_KEY"
  launchctl setenv SHARED_MEMORY_COMPOSER_KEY "$SHARED_MEMORY_COMPOSER_KEY"
  launchctl setenv SHARED_MEMORY_ORCA_KEY "$SHARED_MEMORY_ORCA_KEY"
  note "Keys are available to newly launched apps until logout; .env remains the durable local copy."
else
  SKIPPED+=("load SHARED_MEMORY_* keys before starting fresh agent sessions")
fi
if curl --fail --silent --show-error --retry 20 --retry-delay 2 http://127.0.0.1:8787/health >/dev/null; then
  say "Shared Memory health check passed."
else
  SKIPPED+=("health check: ./bin/memory health")
  warn "The stack is not healthy yet; run ./bin/memory doctor after checking Docker logs."
fi

finish
